//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Form1
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsApp1.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        private FlowLayoutPanel flowLayoutPanel1;
        private Panel panel1;
        private Panel panel2;
        private Panel panel3;
        private Panel panel4;
        private Panel panel5;
        private Label infoLabel;
        private Label greetingLabel;
        private Label labelPair1;
        private Label labelPair2;
        private Label labelPair3;
        private Label labelPair4;
        private Label labelPair5;
        private Label labelTeacher1;
        private Label labelTeacher2;
        private Label labelTeacher3;
        private Label labelTeacher4;
        private Label labelTeacher5;
        private CheckBox autoCheck;
        private Label labelTime1;
        private Label labelTime2;
        private Label labelTime3;
        private Label labelTime4;
        private Label labelTime5;

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            flowLayoutPanel1 = new FlowLayoutPanel();
            panel1 = new Panel();
            labelTime1 = new Label();
            labelTeacher1 = new Label();
            labelPair1 = new Label();
            panel2 = new Panel();
            labelTime2 = new Label();
            labelTeacher2 = new Label();
            labelPair2 = new Label();
            panel3 = new Panel();
            labelTime3 = new Label();
            labelTeacher3 = new Label();
            labelPair3 = new Label();
            panel4 = new Panel();
            labelTime4 = new Label();
            labelTeacher4 = new Label();
            labelPair4 = new Label();
            panel5 = new Panel();
            labelTime5 = new Label();
            labelTeacher5 = new Label();
            labelPair5 = new Label();
            infoLabel = new Label();
            greetingLabel = new Label();
            autoCheck = new CheckBox();
            flowLayoutPanel1.SuspendLayout();
            panel1.SuspendLayout();
            panel2.SuspendLayout();
            panel3.SuspendLayout();
            panel4.SuspendLayout();
            panel5.SuspendLayout();
            SuspendLayout();
            // 
            // flowLayoutPanel1
            // 
            flowLayoutPanel1.BorderStyle = BorderStyle.FixedSingle;
            flowLayoutPanel1.Controls.Add(panel1);
            flowLayoutPanel1.Controls.Add(panel2);
            flowLayoutPanel1.Controls.Add(panel3);
            flowLayoutPanel1.Controls.Add(panel4);
            flowLayoutPanel1.Controls.Add(panel5);
            flowLayoutPanel1.Location = new Point(12, 39);
            flowLayoutPanel1.Name = "flowLayoutPanel1";
            flowLayoutPanel1.Size = new Size(602, 252);
            flowLayoutPanel1.TabIndex = 0;
            // 
            // panel1
            // 
            panel1.BorderStyle = BorderStyle.FixedSingle;
            panel1.Controls.Add(labelTime1);
            panel1.Controls.Add(labelTeacher1);
            panel1.Controls.Add(labelPair1);
            panel1.Location = new Point(0, 0);
            panel1.Margin = new Padding(0);
            panel1.Name = "panel1";
            panel1.Size = new Size(600, 50);
            panel1.TabIndex = 0;
            panel1.Click += panel1_Click;
            // 
            // labelTime1
            // 
            labelTime1.Dock = DockStyle.Right;
            labelTime1.Font = new Font("Consolas", 20.25F, FontStyle.Regular, GraphicsUnit.Point);
            labelTime1.Location = new Point(509, 0);
            labelTime1.Name = "labelTime1";
            labelTime1.Size = new Size(89, 48);
            labelTime1.TabIndex = 2;
            labelTime1.Text = "9:00";
            labelTime1.TextAlign = ContentAlignment.MiddleRight;
            // 
            // labelTeacher1
            // 
            labelTeacher1.AutoSize = true;
            labelTeacher1.Location = new Point(7, 30);
            labelTeacher1.Name = "labelTeacher1";
            labelTeacher1.Size = new Size(78, 15);
            labelTeacher1.TabIndex = 1;
            labelTeacher1.Text = "labelTeacher1";
            // 
            // labelPair1
            // 
            labelPair1.AutoSize = true;
            labelPair1.Cursor = Cursors.Hand;
            labelPair1.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point);
            labelPair1.Location = new Point(5, 5);
            labelPair1.Name = "labelPair1";
            labelPair1.Size = new Size(45, 21);
            labelPair1.TabIndex = 0;
            labelPair1.Text = "Pair1";
            labelPair1.Click += labelPair1_Click;
            // 
            // panel2
            // 
            panel2.BorderStyle = BorderStyle.FixedSingle;
            panel2.Controls.Add(labelTime2);
            panel2.Controls.Add(labelTeacher2);
            panel2.Controls.Add(labelPair2);
            panel2.Location = new Point(0, 50);
            panel2.Margin = new Padding(0);
            panel2.Name = "panel2";
            panel2.Size = new Size(600, 50);
            panel2.TabIndex = 1;
            panel2.Click += panel2_Click;
            // 
            // labelTime2
            // 
            labelTime2.Dock = DockStyle.Right;
            labelTime2.Font = new Font("Consolas", 20.25F, FontStyle.Regular, GraphicsUnit.Point);
            labelTime2.Location = new Point(509, 0);
            labelTime2.Name = "labelTime2";
            labelTime2.Size = new Size(89, 48);
            labelTime2.TabIndex = 3;
            labelTime2.Text = "10:30";
            labelTime2.TextAlign = ContentAlignment.MiddleRight;
            // 
            // labelTeacher2
            // 
            labelTeacher2.AutoSize = true;
            labelTeacher2.Location = new Point(7, 30);
            labelTeacher2.Name = "labelTeacher2";
            labelTeacher2.Size = new Size(78, 15);
            labelTeacher2.TabIndex = 2;
            labelTeacher2.Text = "labelTeacher2";
            // 
            // labelPair2
            // 
            labelPair2.AutoSize = true;
            labelPair2.Cursor = Cursors.Hand;
            labelPair2.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point);
            labelPair2.Location = new Point(5, 5);
            labelPair2.Name = "labelPair2";
            labelPair2.Size = new Size(45, 21);
            labelPair2.TabIndex = 1;
            labelPair2.Text = "Pair2";
            labelPair2.Click += labelPair2_Click;
            // 
            // panel3
            // 
            panel3.BorderStyle = BorderStyle.FixedSingle;
            panel3.Controls.Add(labelTime3);
            panel3.Controls.Add(labelTeacher3);
            panel3.Controls.Add(labelPair3);
            panel3.Location = new Point(0, 100);
            panel3.Margin = new Padding(0);
            panel3.Name = "panel3";
            panel3.Size = new Size(600, 50);
            panel3.TabIndex = 2;
            panel3.Click += panel3_Click;
            // 
            // labelTime3
            // 
            labelTime3.Dock = DockStyle.Right;
            labelTime3.Font = new Font("Consolas", 20.25F, FontStyle.Regular, GraphicsUnit.Point);
            labelTime3.Location = new Point(509, 0);
            labelTime3.Name = "labelTime3";
            labelTime3.Size = new Size(89, 48);
            labelTime3.TabIndex = 4;
            labelTime3.Text = "12:50";
            labelTime3.TextAlign = ContentAlignment.MiddleRight;
            // 
            // labelTeacher3
            // 
            labelTeacher3.AutoSize = true;
            labelTeacher3.Location = new Point(7, 30);
            labelTeacher3.Name = "labelTeacher3";
            labelTeacher3.Size = new Size(78, 15);
            labelTeacher3.TabIndex = 3;
            labelTeacher3.Text = "labelTeacher3";
            // 
            // labelPair3
            // 
            labelPair3.AutoSize = true;
            labelPair3.Cursor = Cursors.Hand;
            labelPair3.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point);
            labelPair3.Location = new Point(5, 5);
            labelPair3.Name = "labelPair3";
            labelPair3.Size = new Size(45, 21);
            labelPair3.TabIndex = 1;
            labelPair3.Text = "Pair3";
            labelPair3.Click += labelPair3_Click;
            // 
            // panel4
            // 
            panel4.BorderStyle = BorderStyle.FixedSingle;
            panel4.Controls.Add(labelTime4);
            panel4.Controls.Add(labelTeacher4);
            panel4.Controls.Add(labelPair4);
            panel4.Location = new Point(0, 150);
            panel4.Margin = new Padding(0);
            panel4.Name = "panel4";
            panel4.Size = new Size(600, 50);
            panel4.TabIndex = 3;
            panel4.Click += panel4_Click;
            // 
            // labelTime4
            // 
            labelTime4.Dock = DockStyle.Right;
            labelTime4.Font = new Font("Consolas", 20.25F, FontStyle.Regular, GraphicsUnit.Point);
            labelTime4.Location = new Point(509, 0);
            labelTime4.Name = "labelTime4";
            labelTime4.Size = new Size(89, 48);
            labelTime4.TabIndex = 5;
            labelTime4.Text = "13:40";
            labelTime4.TextAlign = ContentAlignment.MiddleRight;
            // 
            // labelTeacher4
            // 
            labelTeacher4.AutoSize = true;
            labelTeacher4.Location = new Point(7, 30);
            labelTeacher4.Name = "labelTeacher4";
            labelTeacher4.Size = new Size(78, 15);
            labelTeacher4.TabIndex = 4;
            labelTeacher4.Text = "labelTeacher4";
            // 
            // labelPair4
            // 
            labelPair4.AutoSize = true;
            labelPair4.Cursor = Cursors.Hand;
            labelPair4.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point);
            labelPair4.Location = new Point(5, 5);
            labelPair4.Name = "labelPair4";
            labelPair4.Size = new Size(45, 21);
            labelPair4.TabIndex = 1;
            labelPair4.Text = "Pair4";
            labelPair4.Click += labelPair4_Click;
            // 
            // panel5
            // 
            panel5.BorderStyle = BorderStyle.FixedSingle;
            panel5.Controls.Add(labelTime5);
            panel5.Controls.Add(labelTeacher5);
            panel5.Controls.Add(labelPair5);
            panel5.Location = new Point(0, 200);
            panel5.Margin = new Padding(0);
            panel5.Name = "panel5";
            panel5.Size = new Size(600, 50);
            panel5.TabIndex = 4;
            panel5.Click += panel5_Click;
            // 
            // labelTime5
            // 
            labelTime5.Dock = DockStyle.Right;
            labelTime5.Font = new Font("Consolas", 20.25F, FontStyle.Regular, GraphicsUnit.Point);
            labelTime5.Location = new Point(509, 0);
            labelTime5.Name = "labelTime5";
            labelTime5.Size = new Size(89, 48);
            labelTime5.TabIndex = 6;
            labelTime5.Text = "15:10";
            labelTime5.TextAlign = ContentAlignment.MiddleRight;
            // 
            // labelTeacher5
            // 
            labelTeacher5.AutoSize = true;
            labelTeacher5.Location = new Point(5, 30);
            labelTeacher5.Name = "labelTeacher5";
            labelTeacher5.Size = new Size(78, 15);
            labelTeacher5.TabIndex = 5;
            labelTeacher5.Text = "labelTeacher5";
            // 
            // labelPair5
            // 
            labelPair5.AutoSize = true;
            labelPair5.Cursor = Cursors.Hand;
            labelPair5.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point);
            labelPair5.Location = new Point(5, 5);
            labelPair5.Name = "labelPair5";
            labelPair5.Size = new Size(45, 21);
            labelPair5.TabIndex = 2;
            labelPair5.Text = "Pair5";
            labelPair5.Click += labelPair5_Click;
            // 
            // infoLabel
            // 
            infoLabel.Location = new Point(142, 299);
            infoLabel.Name = "infoLabel";
            infoLabel.Size = new Size(470, 20);
            infoLabel.TabIndex = 1;
            infoLabel.Text = "infoLabel";
            infoLabel.TextAlign = ContentAlignment.TopRight;
            // 
            // greetingLabel
            // 
            greetingLabel.AutoSize = true;
            greetingLabel.Font = new Font("Microsoft YaHei", 14.25F, FontStyle.Regular, GraphicsUnit.Point);
            greetingLabel.Location = new Point(12, 7);
            greetingLabel.Name = "greetingLabel";
            greetingLabel.Size = new Size(138, 25);
            greetingLabel.TabIndex = 2;
            greetingLabel.Text = "greetingLabel";
            // 
            // autoCheck
            // 
            autoCheck.AutoSize = true;
            autoCheck.Checked = true;
            autoCheck.CheckState = CheckState.Checked;
            autoCheck.Location = new Point(12, 299);
            autoCheck.Name = "autoCheck";
            autoCheck.Size = new Size(124, 19);
            autoCheck.TabIndex = 3;
            autoCheck.Text = "Автопідключення";
            autoCheck.UseVisualStyleBackColor = true;
            // 
            // Form1
            // 
            ClientSize = new Size(626, 323);
            Controls.Add(autoCheck);
            Controls.Add(greetingLabel);
            Controls.Add(infoLabel);
            Controls.Add(flowLayoutPanel1);
            Icon = (Icon)resources.GetObject("$this.Icon");
            Name = "Form1";
            Text = "Розклад";
            FormClosing += Form1_FormClosing;
            flowLayoutPanel1.ResumeLayout(false);
            panel1.ResumeLayout(false);
            panel1.PerformLayout();
            panel2.ResumeLayout(false);
            panel2.PerformLayout();
            panel3.ResumeLayout(false);
            panel3.PerformLayout();
            panel4.ResumeLayout(false);
            panel4.PerformLayout();
            panel5.ResumeLayout(false);
            panel5.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }
    }
}
